// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYY_tWQ84vNyX34yaJsabriGQG-ybTVvg',
    appId: '1:32981608493:web:39887bb72c9de19668b0a4',
    messagingSenderId: '32981608493',
    projectId: 'task-manager-app-22a90',
    authDomain: 'task-manager-app-22a90.firebaseapp.com',
    storageBucket: 'task-manager-app-22a90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-MUD96DIZKvhaYhgMdGSZBht8ARtxIQ',
    appId: '1:32981608493:android:8b6c7695ff1589fc68b0a4',
    messagingSenderId: '32981608493',
    projectId: 'task-manager-app-22a90',
    storageBucket: 'task-manager-app-22a90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4A21DnWciIxlSciQY5NziREcGt85hRY',
    appId: '1:32981608493:ios:e21231e7cd3fe06568b0a4',
    messagingSenderId: '32981608493',
    projectId: 'task-manager-app-22a90',
    storageBucket: 'task-manager-app-22a90.appspot.com',
    iosBundleId: 'com.example.taskManagerApp',
  );
}
